#!/bin/bash

# Dotfiles install helper.
#   2016 @leonjza

# This script is structured in the following way:
#
#   Default variable values such as git path & commandline arguments
#   Helper functions such as color output
#   Function definitions with the *actual* logic
#   Small helper to ensure the commands needed for this installer is available
#   Commandline argument parser at the bottom to decide what gets called
#
#   For more, see the README file at $gitorigin

set -e

# static variables
gitpath="$HOME/.dotfiles"
gitorigin="https://github.com/leonjza/dotfiles.git"
debug=true

# configurations this script knows how to setup
declare -a configurations=("all" "none" "zsh" "vim" "tmux")

# defaults for commandline options
install_target="no"
uninstall_target="no"
update=false
showusage="no"

# defaults for file & config locations
oh_my_zsh="$HOME/.oh-my-zsh"
zsh_rc="$HOME/.zshrc"
vim_plugin_dir="$HOME/.vim"
vim_rc="$HOME/.vimrc"
tmux_conf="$HOME/.tmux.conf"

# helper functions
# colors!
function echo_green() { echo -e "$(tput setaf 2; tput bold)$*$(tput sgr0)"; }
function echo_red() { echo -e "$(tput setaf 1)$*$(tput sgr0)"; }
function echo_yellow() { echo -e "$(tput setaf 3)$*$(tput sgr0)"; }
function echo_debug() { if [ "$debug" = true ]; then echo -e "$(tput setaf 3; tput bold)>>> $*$(tput sgr0)"; fi }
# directories!
function pushd() { command pushd "$@" > /dev/null; }
function popd() { command popd "$@" > /dev/null; }
# curl
function curl() { command curl -fsSL "$1" -o "$2"; }

# app logic
function usage() {

    cat <<EOF
    Dotfiles installer/updater
        2016 @leonjza

    Usage: install [argument] [option]

    Examples (install)
        install --i all
        install --install
        install --install all
        install --install vim

    Examples (remove):
        install -r all
        install --remove all
        install --remove vim

    Examples (update):
        install -u
        install --update
EOF

}

function prepare_git() {

    echo_debug "Preparing git folder at: $gitpath"

    # if there is already a file called .dotfiles, error out for manual inspection
    if [[ -f $gitpath ]]; then

        echo_red "$gitpath appears to be an existing file. Inspect/remove it first!"
        exit 1

    fi

    # if the path does not exist, just clone there. easy.
    if [[ ! -d $gitpath ]]; then

        echo_yellow "Git repo in $gitpath does not exist. Cloning dotfiles repository: $gitorigin"
        git clone $gitorigin $gitpath
        return

    fi

    # some more work is needed to to see if the repo is sane
    echo_debug "$gitpath exists, inspecting it"
    pushd $gitpath

    # check if we are inside a valid git repository
    valid_repo=$(set +e; git rev-parse --is-inside-work-tree 2>/dev/null; set -e)
    if [[ ! "$valid_repo" = true ]]; then

        echo_red "$gitpath is a directory, but not a valid git repository. Move/delete it to continue"
        exit 1

    fi

    # get the remote origin of the existing repository and check it
    localorigin=$(git config --get remote.origin.url)
    echo_debug "Local git origin is: $localorigin"

    if [[ ! "$localorigin" = $gitorigin ]]; then

        echo_red "It looks like the origin for the local dotfiles repo does not match."
        echo_red "The local origin is $localorigin and it should be $gitorigin"
        exit 2

    fi

	popd

    echo_green "Git repository at $gitpath looks OK"

}

function validate_configuration() {

    local seeking=$1
    echo_debug "Looking for '$seeking' in the valid configurations.."
    for element in "${configurations[@]}"; do

        if [[ "$element" == "$seeking" ]]; then
            echo_green "Configuration '$seeking' looks OK"
            return
        fi

    done

    echo_red "$seeking is not a valid configuration"
    exit 1

}

function install_components() {

    # check that the install target is something we know if
    validate_configuration $install_target

    # Ensure that we have the source repository ready in $gitpath
    prepare_git
    echo_debug "Installing: $install_target"

    case $install_target in
        none)
            echo_green "Installing nothing..."
            return
        ;;
        all)
            install_zsh
			install_vim
			install_tmux
        ;;
		zsh)
			install_zsh
		;;
		vim)
			install_vim
		;;
		tmux)
			install_tmux
		;;
    esac

}

function install_zsh() {

    local temp="$(mktemp)"
    echo_green "Installing ZSH configuration"

    # make sure zsh is available
    if ! hash zsh 2>/dev/null; then
        echo_red "zsh is not installed or in your PATH. Not installing this configuration."
        return
    fi

    echo_green "Downloading oh-my-zsh installer"
    echo_debug "Saving installer to $temp"
    curl "https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh" $temp

    echo_debug "Preventing the installer from starting ZSH when its done"
    sed -i -r "s/env zsh//" $temp

    echo_green "Running oh-my-zsh installer..."
    echo_debug "Using sh to run $temp"
    sh $temp
    echo_debug "Removing downloaded installer"
    rm -f $temp

    echo_green "Installing plugins"
    echo_debug "Using oh-my-zsh directory: $oh_my_zsh/custom/plugins"

    # Syntax highlighting
    if [[ ! -d "$oh_my_zsh/custom/plugins/zsh-syntax-highlighting" ]]; then
        git clone git://github.com/zsh-users/zsh-syntax-highlighting.git $oh_my_zsh/custom/plugins/zsh-syntax-highlighting
    else
        echo_yellow "Syntax highligthing plugin already exists."
    fi

    # Auto suggestions
    if [[ ! -d "$oh_my_zsh/custom/plugins/zsh-autosuggestions" ]]; then
        git clone git://github.com/zsh-users/zsh-autosuggestions $oh_my_zsh/custom/plugins/zsh-autosuggestions
    else
        echo_yellow "Autosuggestions plugin already exists."
    fi

    echo_green "Installing configuration file"

    if [[ -f "$zsh_rc" ]]; then
        echo_yellow "Backing up existing zshrc to $HOME/zshrc.backup"
        mv $zsh_rc $HOME/zshrc.backup
    fi

    echo_debug "Symlinking $gitpath/zshrc to $zsh_rc"
    ln -s $gitpath/zshrc $zsh_rc

	echo_green "ZSH config install complete!"

}

function install_vim() {

    echo_green "Installing Vim configuration"

    # make sure vim is available
    if ! hash vim 2>/dev/null; then
        echo_red "vim is not installed or in your PATH. Not installing this configuration."
        return
    fi

	echo_debug "Preparing the vim plugin directory at $vim_plugin_dir"
	mkdir -p $vim_plugin_dir

	echo_green "Installing Vim Plugins"

	# Vundle
	if [[ ! -d "$vim_plugin_dir/bundle/Vundle.vim" ]]; then
		git clone https://github.com/gmarik/Vundle.vim $vim_plugin_dir/bundle/Vundle.vim
	else
		echo_yellow "Vundle already exists."
	fi

	# Molokai
	if [[ ! -d "$vim_plugin_dir/bundle/molokai" ]]; then
		git clone https://github.com/tomasr/molokai $vim_plugin_dir/bundle/molokai
	else
		echo_yellow "Molokai color scheme already exists."
	fi

    echo_green "Installing configuration file"

    if [[ -f "$vim_rc" ]]; then
        echo_yellow "Backing up existing vimrc to $HOME/vimrc.backup"
        mv $vim_rc $HOME/vimrc.backup
    fi

    echo_debug "Symlinking $gitpath/vimrc to $vim_rc"
    ln -s $gitpath/vimrc $vim_rc

	echo_green "Running vim plugin installer"
	vim +PluginInstall +qall

	echo_green "Vim config install complete!"

}

function install_tmux() {

    echo_green "Installing Tmux configuration"

    # make sure tmux is available
    if ! hash tmux 2>/dev/null; then
        echo_red "tmux is not installed or in your PATH. Not installing this configuration."
        return
    fi

    echo_green "Installing configuration file"

    if [[ -f "$tmux_conf" ]]; then
        echo_yellow "Backing up existing tmuxconf to $HOME/tmuxconf.backup"
        mv $tmux_conf $HOME/tmuxconf.backup
    fi

    echo_debug "Symlinking $gitpath/tmux.conf to $tmux_conf"
    ln -s $gitpath/tmux.conf $tmux_conf

	echo_green "Tmux config install complete!"
}

function uninstall_components() {

    # check that the uninstall target is something we know if
    validate_configuration $uninstall_target

    # Ensure that we have the source repository ready in $gitpath
    echo_debug "Uninstalling: $uninstall_target"

    case $uninstall_target in
        none)
            echo_green "Uninstalling nothing..."
            return
        ;;
        all)
            echo_green "Uninstalling everything"

            # restore the shell back to bash
            echo_yellow "Changing your shell back to bash!"
            chsh -s $(grep /bash$ /etc/shells | tail -1)

            rm -Rf $oh_my_zsh
            rm -f $zsh_rc
            rm -Rf $vim_plugin_dir
            rm -f $vim_rc
            rm -f $tmux_conf
            rm -Rf $gitpath
        ;;
		vim)
			echo_green "Uninstalling Vim configuration"
            rm -Rf $vim_plugin_dir
            rm -f $vim_rc
			#TODO Restore backed up rc file
		;;
    esac

}

function update_repo() {

    prepare_git

    echo_debug "Running git pull on $gitpath"
    pushd $gitpath
    git pull
    popd
}

# start by checking the software needed by this installer
# if we cant find it, rather die
for cmd in "curl" "git"; do

    if ! hash $cmd 2>/dev/null; then
        echo_red "'$cmd' can not be found. Please install it before using this script"
        exit 2
    fi
    echo_debug "Using $cmd from $(which $cmd)"

done

# parse commandline arguments
if [[ $# -gt 1 ]]; then

    while [[ $# -gt 1 ]]; do
        case $1 in
        -i|--install)
        install_target="$2"
        shift # past argument
        ;;
        -r|--remove)
        uninstall_target="$2"
        shift # past argument
        ;;
        -u|--update)
        update=true
        shift # past argument
        ;;
        *)
        showusage="yes"
        ;;
    esac

    shift # past argument or value
    done
else
    echo_debug "Running usage(), no args -gt 1 found"
    usage
fi

# usage
if [ "$showusage" = "yes" ]; then
    usage
    exit 2
fi

# install
if [[ ! "$install_target" = "no" ]]; then
    echo_green "Running install on: $install_target"
    install_components
fi

if [[ ! "$uninstall_target" = "no" ]]; then
    echo_green "Running uninstall on: $uninstall_target"
    uninstall_components
fi

if [[ "$update" = true ]]; then
    echo_green "Running repo update"
    update_repo
fi
