" Gotta be first
set nocompatible
set modeline

filetype on

" Set the runtimepath for Vundle
set rtp+=~/.vim/bundle/Vundle.vim

" To add extra configurations, add your file, numbered
" in the order you want it loaded to:
"   ~/.dotfiles.d/vimrc.d/
"
" The file name should end with .vim to be loaded correctly.

" Load all user vimconfig files. scripts are globbed lexicographically
" and can therefore be prefixed numerically.
for f in split(glob('~/.dotfiles.d/vimrc.d/*.vim'), '\n')
    exe 'source' f
endfor
