# Path to your oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="af-magic"

# Disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Fetch suggestions asynchronously.
# https://github.com/zsh-users/zsh-autosuggestions#enable-asynchronous-mode
ZSH_AUTOSUGGEST_USE_ASYNC="true"

# Display red dots whilst waiting for completion.
# Broken on macOS:
#   https://github.com/zsh-users/zsh-autosuggestions/issues/14#issuecomment-104721378
#COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(sudo git zsh-syntax-highlighting zsh-autosuggestions docker extract httpie colored-man-pages)

# Load up Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

# Clear the RPROMPT
RPROMPT=""

# Adding your own configurations should be done by adding files
# to the following directory:
#   ~/.dotfiles.d/zshrc.d/
#
# The filename should end .zsh to be loaded correctly!

# Load all *.zsh files from ~/.dotfiles.d/zshrc.d directory
if [ -d $HOME/.dotfiles.d/zshrc.d ]; then

  for file in $HOME/.dotfiles.d/zshrc.d/*.zsh; do
    source $file
  done

fi
