# Path to your oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="af-magic"

# Timestamp history output
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting zsh-autosuggestions docker extract httpie colored-man-pages fzf)

# Load up Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

# Clear the RPROMPT
RPROMPT=""

# Update theme to not include the horizontal ---- line
PROMPT='$FG[032]%~\
$(git_prompt_info) \
$FG[105]%(!.#.»)%{$reset_color%} '
PROMPT2='%{$fg[red]%}\ %{$reset_color%}'

# If you want to have the hostname as part of the prompt, edit
# ~/.dotfiles.d/zshrc.d/local.zsh and add the line:
# PROMPT="%{$fg[green]%}%m%{$reset_color%} ${PROMPT}"

# Adding your own configurations should be done by adding files
# to the following directory:
#   ~/.dotfiles.d/zshrc.d/
#
# The filename should end .zsh to be loaded correctly!

# Load all *.zsh files from ~/.dotfiles.d/zshrc.d directory
if [ -d $HOME/.dotfiles.d/zshrc.d ]; then

  for file in $HOME/.dotfiles.d/zshrc.d/*.zsh; do
    source $file
  done

fi

