#!/bin/bash

# Sublime Text 3 setup script. Part 1

sublime_dir="$HOME/Library/Application Support/Sublime Text 3"
packages_dir="$sublime_dir/Installed Packages"
user_dir="$sublime_dir/Packages/User"

if [[ ! "$(uname)" == "Darwin" ]]; then

    echo "This can only run on OSX. Sorry!"
    exit 1
fi

mkdir -p "$packages_dir"
mkdir -p "$user_dir"

echo "Downloading Package Control..."
curl -fsSL "https://sublime.wbond.net/Package Control.sublime-package" -o "$packages_dir/Package Control.sublime-package"
echo "Configuring desired packages"
cp -f "Package Control.sublime-settings" "$user_dir"

echo "Done. Launch Sublime and press ctrl +\` for a status!"
